export const NURSERIES_FETCHED = 'NURSERIES_FETCHED'
export const NURSERIES_SET_CURRENT = 'NURSERIES_SET_CURRENT'

export const SAMPLES_FETCHED = 'SAMPLES_FETCHED'

export const PARAMS_FETCHED = 'PARAMS_FETCHED'

export const USER_LOGEDIN = 'USER_LOGEDIN'