export const NURSERIES_FETCHED = 'NURSERIES_FETCHED'
export const NURSERIES_SET_CURRENT = 'NURSERIES_SET_CURRENT'

export const SAMPLES_FETCHED = 'SAMPLES_FETCHED'

export const PARAMS_FETCHED = 'PARAMS_FETCHED'

export const USER_LOGEDIN = 'USER_LOGEDIN'
export const USER_LOGEDOUT = 'USER_LOGEDOUT'

export const SHOW_LOGOUT_MODAL = 'SHOW_LOGOUT_MODAL'
export const HIDE_LOGOUT_MODAL = 'HIDE_LOGOUT_MODAL'

export const PERMISSIONS_FETCHED = 'PERMISSIONS_FETCHED'